<template>
  <!-- <nav>
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
  </nav>
  <router-view/> -->
  <div id="app">
    <div class="titleBar">
      <div class="title">
        <div class="logo">
          <img src="@/assets/logo.png">
        </div>
        <div class="txt">文件系统教学辅助工具</div>
      </div>
      <div class="windowTool">
        <div @click="minisize">
          <i class="iconfont iconminisize"></i>
        </div>
        <div v-if="isMaxSize" @click="restore">
          <i class="iconfont iconrestore"></i>
        </div>
        <div v-else @click="maxsize">
          <i class="iconfont iconmaxsize"></i>
        </div>
        <div @click="close" class="close">
          <i class="iconfont iconclose"></i>
        </div>
      </div>
    </div>
    <div class="content">
      <div style="height: 50px;display: flex;">
        <!-- <nav>
          <router-link to="/module1" class="kongjian1">文件系统基本信息展示</router-link> |
          <router-link to="/about">文件系统组织结构展示</router-link> |
          <router-link to="/module3">对文件操作的磁盘变化</router-link>
        </nav> -->
        <router-link to="/module1" class="kongjian kongjian1">
          <div class="kongjian-txt kongjian-txt1">文件系统基本信息展示</div>
        </router-link>
        <router-link to="/about" class="kongjian kongjian2">
          <div class="kongjian-txt kongjian-txt1">文件系统组织结构展示</div>
        </router-link>
        <router-link to="/module3" class="kongjian kongjian3">
          <div class="kongjian-txt kongjian-txt3">对文件操作的磁盘变化</div>
        </router-link>
      </div> 
      
      <router-view/>
    </div>
  </div>
</template>

<script>
let { remote } = require("electron");

export default {
  data() {
    return {
      isMaxSize: false,
    }
  },
  // mounted() {
  //   let win = remote.getCurrentWindow();
  //   win.on('maximize', _ => {
  //     this.isMaxSize = true;
  //     // this.setState();
  //   })
  //   win.on('unmaximize', _ => {
  //     this.isMaxSize = false;
  //     // this.setState();
  //   })
  // },
  methods: {
    close() {
      remote.getCurrentWindow().close();
    },
    minisize() {
      remote.getCurrentWindow().minimize();
    },
    restore() {
      remote.getCurrentWindow().restore();
      this.isMaxSize = false;
    },
    maxsize() {
      remote.getCurrentWindow().maximize();
      this.isMaxSize = true;
    }
  }
}
</script>

<style  lang="scss" >
#app {
  text-align: center;margin: 0px; padding: 0px;
  height: 100%; overflow: hidden;
  box-sizing: border-box;
  border: 1px solid #f5222d;
  display: flex;
  flex-direction: column;
  
  background-image: url('./assets/ispazio-5.jpg');
  background-size: cover;
}
body, html {
  margin: 0px;
  padding: 0px;
  overflow: hidden;
  height: 100%;
}
nav {
  padding: 30px;

  a {
    font-weight: bold;
    color: #2c3e50;

    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
</style>

<style lang="scss" scoped>
@import url(https://at.alicdn.com/t/font_1378132_s4e44adve5.css);
.titleBar {
  height: 38px;
  line-height: 36px;
  background: #fff1f0;
  display: flex;
  border-bottom: 1px solid #f5222d;
}
.title {
  flex: 1;
  display: flex;
  -webkit-app-region: drag;
  .logo {
    padding-left: 8px;
    padding-right: 6px;
    img {
      width: 20px;
      height: 20px;
      margin-top: 7px;
    }
    .txt {text-align: left; flex: 1;}
  } 
}
.windowTool {
    div {
      color: #888;
      height: 100%;
      width: 38px;
      display: inline-block;
      cursor: pointer;
      i {font-size: 12px;}
      &:hover {background: #ffccc7;}
    }
    .close:hover {color: #fff;background: #ff4d4f;}
  }
.content {
  flex: 1;
  overflow-y: auto;
  overflow-x: auto;
  // background: #42b983;
}

.flip-horizontal-bottom {
-webkit-animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) ;
animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) ;
}

// .flip-horizontal-bottom:hover {
// -webkit-animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) ;
// animation: flip-horizontal-bottom 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) ;
// }

/* ----------------------------------------------
 * Generated by Animista on 2022-5-30 17:2:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-horizontal-bottom
 * ----------------------------------------
 */
@-webkit-keyframes flip-horizontal-bottom {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-180deg);
            transform: rotateX(-180deg);
  }
}
@keyframes flip-horizontal-bottom {
  0% {
    -webkit-transform: rotateX(0);
            transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-180deg);
            transform: rotateX(-180deg);
  }
}

.kongjian {
  width: 430px;
  height: 80px;
  border-radius: 20px;
  // background-color: #f5222d;
  display: flex;
  flex-direction: row;
  margin: 10px;
  margin-right: 43px;
  transition-duration: .5s;
  text-decoration: none;
  color: #2c3e50;
}

.kongjian:hover {
  -webkit-transform: scale(1.2);
}

.kongjian1 {
  margin-left: 43px;
  background: white;
  display: flex;
  flex-direction: row;
}

.kongjian2 {
  background: #FFF480;
  display: flex;
  flex-direction: row;
}

.kongjian3 {
  background: #1B1B1F;
  display: flex;
  flex-direction: row;
}

.kongjian-txt {
  
  // padding: 5px;
  width: 480px;
  height: 80px;
  margin-top: 16px;
  // display: flex;
  text-align: center;
  font-family: "Satoshi-Variable","Helvetica Neue","Helvetica","Arial",sans-serif;
  font-size: 30px;
  font-weight: bold;
}

.kongjian-txt1 {
  color: black;
}
.kongjian-txt3 {
  color: white;
}
</style>